WebApplication3/WebApplication3/Models/Cat.cs
namespace WebApplication3.Models
{
    public class Cat
    {
        public int Id { get; set; }
        public string? Name { get; set; }

        public int Age { get; set; }

        public string? Breed { get; set; }

        public string? URL { get; set; } 
    }
}

WebApplication3/WebApplication3/Models/ErrorViewModel.cs
namespace WebApplication3.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication3/WebApplication3/Controllers/CatController.cs
using Fluffy.Contracts;
using Microsoft.AspNetCore.Mvc;
using WebApplication3.Data;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    public class CatController : Controller
    {
        private ICatService catService;
        

        public CatController(ICatService catService)
        {

         
            this.catService = catService;
        }
        public IActionResult Index()
        {
            var cats = this.catService.GetAll();
            return View(cats);
        }

        public IActionResult Add()
        {

            return View();
        }
        public IActionResult Create(Cat CattobeCreated)
        {
            this.catService.Create(CattobeCreated);
            return RedirectToAction("Index"); 
        }
        public IActionResult Details (int id)
        {
            Cat cat = this.catService.GetCat(id);
          
            return View(cat);
        }
    }
}

WebApplication3/WebApplication3/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication3/WebApplication3/Views/Cat/Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Cat //винаги да казваме какъв е модела
<form asp-controller="Cat" asp-action="Create" method="post" class="col-lg-4">

    
   <div>
       <label for="name">Name</label>
    <input asp-for="Name" name="name">
   </div>

   <div>
       <label for="age">Age</label>
        <input asp-for="Age" name="age" >
   </div>
   <div>
       <label for="breed">Breed</label>
   <input asp-for="Breed" name="breed">
   </div>
   
   <div><label for="url">URL</label>
   <input asp-for="URL" name="url">
   </div>
  
   <input type = "submit" value="Add" />
</form>

WebApplication3/WebApplication3/Views/Cat/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    @model Cat
    
    
    <h1>@Model.Name </h1>
    <h2>@Model.Age </h2>
    <h3>@Model.Breed</h3>
    <img src="@Model.URL" alt="@Model.Name" style="width:300px"/>
    
}

WebApplication3/WebApplication3/Views/Cat/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
@model List<Cat>
    <h1>Fluffy List Cats</h1>

    <ul>
        @for (int i=0; i <Model.Count; i++)
        {
            var currentCat = Model[i];
             <li><a asp-controller="Cat" asp-action="Details" asp-route-id="@currentCat.Id">@currentCat.Name</a></li>
        }

    </ul>
    //tag helper
    <a asp-controller="Cat" asp-action="Add" class="btn btn-primary">Add</a>

   
}

WebApplication3/WebApplication3/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApplication3/WebApplication3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication3</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebApplication3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>